apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- config-map.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
commonLabels:
  kustomize.component: pytorch-operator
images:
  - name: gcr.io/kubeflow-demo-256908/3rdparty/kubeflow-images-public/pytorch-operator
    newName: gcr.io/kubeflow-demo-256908/3rdparty/kubeflow-images-public/pytorch-operator
    newTag: v1.0.0-rc.0
